language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "kcc112"
    source:
      token: "$SONAR_TOKEN"
jdk:
  - oraclejdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=kcc112_backend-zzpj
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'